# docker/docker-compose.gpu.yml

services:
  blender-service:
    environment:
      - GPU_AVAILABLE=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  colmap-service:
    environment:
      - GPU_AVAILABLE=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  alicevision-service:
    environment:
      - GPU_AVAILABLE=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]